import { Router } from "express";

// Géolocalisation automatique — basée sur les headers IP fournis par Vercel
// sur les fonctions serverless : x-vercel-ip-country (code ISO 3166-1 alpha-2),
// x-vercel-ip-country-region, x-vercel-ip-city, x-vercel-ip-latitude/longitude.
// En dev local (aucun header), la réponse a des champs vides : le client
// retombe alors sur la géolocalisation du navigateur (reverse geocoding).

const router = Router();

// Carte ISO 3166-1 alpha-2 → nom français (alignée sur la liste COUNTRIES du
// client). Incomplète volontairement : si le code est inconnu, on renvoie quand
// même le code brut et le client essaiera un match par nom de ville/région.
const ISO_TO_FR = {
  AD: "Andorre",
  AE: "Émirats arabes unis",
  AF: "Afghanistan",
  AL: "Albanie",
  AO: "Angola",
  AR: "Argentine",
  AT: "Autriche",
  AU: "Australie",
  AZ: "Azerbaïdjan",
  BD: "Bangladesh",
  BE: "Belgique",
  BF: "Burkina Faso",
  BG: "Bulgarie",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Bénin",
  BN: "Brunei",
  BO: "Bolivie",
  BR: "Brésil",
  BS: "Bahamas",
  BT: "Bhoutan",
  BY: "Biélorussie",
  CA: "Canada",
  CD: "République démocratique du Congo",
  CF: "Centrafrique",
  CG: "Congo",
  CH: "Suisse",
  CI: "Côte d'Ivoire",
  CL: "Chili",
  CM: "Cameroun",
  CN: "Chine",
  CO: "Colombie",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cap-Vert",
  CY: "Chypre",
  CZ: "Tchéquie",
  DE: "Allemagne",
  DJ: "Djibouti",
  DK: "Danemark",
  DZ: "Algérie",
  EC: "Équateur",
  EE: "Estonie",
  EG: "Égypte",
  ER: "Érythrée",
  ES: "Espagne",
  ET: "Éthiopie",
  FI: "Finlande",
  FJ: "Fidji",
  FR: "France",
  GA: "Gabon",
  GB: "Royaume-Uni",
  GE: "Géorgie",
  GH: "Ghana",
  GM: "Gambie",
  GN: "Guinée",
  GQ: "Guinée équatoriale",
  GR: "Grèce",
  GT: "Guatemala",
  GW: "Guinée-Bissau",
  HN: "Honduras",
  HR: "Croatie",
  HT: "Haïti",
  HU: "Hongrie",
  ID: "Indonésie",
  IE: "Irlande",
  IL: "Israël",
  IN: "Inde",
  IQ: "Irak",
  IR: "Iran",
  IS: "Islande",
  IT: "Italie",
  JM: "Jamaïque",
  JO: "Jordanie",
  JP: "Japon",
  KE: "Kenya",
  KG: "Kirghizistan",
  KH: "Cambodge",
  KM: "Comores",
  KR: "Corée du Sud",
  KW: "Koweït",
  LB: "Liban",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Lituanie",
  LU: "Luxembourg",
  LV: "Lettonie",
  LY: "Libye",
  MA: "Maroc",
  MD: "Moldavie",
  MG: "Madagascar",
  MK: "Macédoine du Nord",
  ML: "Mali",
  MM: "Myanmar",
  MN: "Mongolie",
  MR: "Mauritanie",
  MT: "Malte",
  MU: "Maurice",
  MV: "Maldives",
  MW: "Malawi",
  MX: "Mexique",
  MY: "Malaisie",
  MZ: "Mozambique",
  NA: "Namibie",
  NE: "Niger",
  NG: "Nigéria",
  NI: "Nicaragua",
  NL: "Pays-Bas",
  NO: "Norvège",
  NP: "Népal",
  NZ: "Nouvelle-Zélande",
  OM: "Oman",
  PA: "Panama",
  PE: "Pérou",
  PG: "Papouasie-Nouvelle-Guinée",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Pologne",
  PT: "Portugal",
  PY: "Paraguay",
  QA: "Qatar",
  RO: "Roumanie",
  RS: "Serbie",
  RU: "Russie",
  RW: "Rwanda",
  SA: "Arabie saoudite",
  SC: "Seychelles",
  SD: "Soudan",
  SE: "Suède",
  SG: "Singapour",
  SI: "Slovénie",
  SK: "Slovaquie",
  SL: "Sierra Leone",
  SN: "Sénégal",
  SO: "Somalie",
  SR: "Suriname",
  SS: "Soudan du Sud",
  SV: "Salvador",
  SY: "Syrie",
  SZ: "Eswatini",
  TD: "Tchad",
  TG: "Togo",
  TH: "Thaïlande",
  TJ: "Tadjikistan",
  TM: "Turkménistan",
  TN: "Tunisie",
  TR: "Turquie",
  TT: "Trinité-et-Tobago",
  TW: "Taïwan",
  TZ: "Tanzanie",
  UA: "Ukraine",
  UG: "Ouganda",
  US: "États-Unis",
  UY: "Uruguay",
  UZ: "Ouzbékistan",
  VE: "Venezuela",
  VN: "Vietnam",
  YE: "Yémen",
  ZA: "Afrique du Sud",
  ZM: "Zambie",
  ZW: "Zimbabwe",
};

router.get("/", (req, res) => {
  res.set("Cache-Control", "public, s-maxage=300, max-age=150");
  const code = String(req.headers["x-vercel-ip-country"] || "").toUpperCase();
  const region = String(req.headers["x-vercel-ip-country-region"] || "") || null;
  const city = String(req.headers["x-vercel-ip-city"] || "") || null;
  const lat = req.headers["x-vercel-ip-latitude"]
    ? Number(req.headers["x-vercel-ip-latitude"])
    : null;
  const lon = req.headers["x-vercel-ip-longitude"]
    ? Number(req.headers["x-vercel-ip-longitude"])
    : null;
  res.json({
    ok: true,
    code: code || null,
    country: code ? ISO_TO_FR[code] || null : null,
    region,
    city,
    lat,
    lon,
  });
});

export default router;