const CURRENCIES = {
  'Cameroun': 'XAF',
  "Côte d'Ivoire": 'XOF',
  'Sénégal': 'XOF',
  'Mali': 'XOF',
  'Burkina Faso': 'XOF',
  'Niger': 'XOF',
  'Togo': 'XOF',
  'Bénin': 'XOF',
  'Guinée': 'GNF',
  'Gabon': 'XAF',
  'Tchad': 'XAF',
  'République du Congo': 'XAF',
  'République démocratique du Congo': 'CDF',
  'Guinée équatoriale': 'XAF',
  'République centrafricaine': 'XAF',
  'Rwanda': 'RWF',
  'Burundi': 'BIF',
  'Kenya': 'KES',
  'Nigeria': 'NGN',
  'Ghana': 'GHS',
  'Afrique du Sud': 'ZAR',
  'Ouganda': 'UGX',
  'Tanzanie': 'TZS',
  'Éthiopie': 'ETB',
  'Mozambique': 'MZN',
  'Angola': 'AOA',
  'Madagascar': 'MGA',
  'Île Maurice': 'MUR',
  'Zambie': 'ZMW',
  'Zimbabwe': 'ZWL',
  'Libye': 'LYD',
  'Mauritanie': 'MRU',
  'Soudan': 'SDG',
  'Algérie': 'DZD',
  'Maroc': 'MAD',
  'Tunisie': 'TND',
  'Égypte': 'EGP',
  'France': 'EUR',
  'Belgique': 'EUR',
  'Suisse': 'CHF',
  'Luxembourg': 'EUR',
  'Autriche': 'EUR',
  'Allemagne': 'EUR',
  'Espagne': 'EUR',
  'Italie': 'EUR',
  'Portugal': 'EUR',
  'Pays-Bas': 'EUR',
  'Pologne': 'PLN',
  'Roumanie': 'RON',
  'Grèce': 'EUR',
  'Irlande': 'EUR',
  'Suède': 'SEK',
  'Norvège': 'NOK',
  'Danemark': 'DKK',
  'Finlande': 'EUR',
  'Royaume-Uni': 'GBP',
  'Russie': 'RUB',
  'Turquie': 'TRY',
  'Ukraine': 'UAH',
  'Canada': 'CAD',
  'États-Unis': 'USD',
  'Mexique': 'MXN',
  'Brésil': 'BRL',
  'Argentine': 'ARS',
  'Colombie': 'COP',
  'Chili': 'CLP',
  'Pérou': 'PEN',
  'Venezuela': 'VES',
  'Équateur': 'USD',
  'Chine': 'CNY',
  'Japon': 'JPY',
  'Inde': 'INR',
  'Corée du Sud': 'KRW',
  'Indonésie': 'IDR',
  'Malaisie': 'MYR',
  'Thaïlande': 'THB',
  'Vietnam': 'VND',
  'Philippines': 'PHP',
  'Pakistan': 'PKR',
  'Bangladesh': 'BDT',
  'Arabie saoudite': 'SAR',
  'Émirats arabes unis': 'AED',
  'Qatar': 'QAR',
  'Israël': 'ILS',
  'Singapour': 'SGD',
  'Australie': 'AUD',
  'Nouvelle-Zélande': 'NZD',
};

export function defaultCurrencyFor(country) {
  return CURRENCIES[country] || 'XAF';
}

const CODE_RE = /^[A-Z]{3}$/;

export function validCurrency(code) {
  return typeof code === 'string' && CODE_RE.test(code.trim().toUpperCase());
}